Tensor Manipulations & Reshaping

Task: Tensor Reshaping & Operations

1.	Create a random tensor of shape (4, 6).
2.	Find its rank and shape using TensorFlow functions.
3.	Reshape it into (2, 3, 4) and transpose it to (3, 2, 4).
4.	Broadcast a smaller tensor (1, 4) to match the larger tensor and add them.
5.	Explain how broadcasting works in TensorFlow.

Expected Output:

•	Print rank and shape of the tensor before and after reshaping/transposing.


In [ ]:
# necessary imports
import tensorflow as tf

In [ ]:
#	Create a random tensor of shape (4, 6).
tensor = tf.random.normal([4,6])

In [ ]:
#	Find its rank and shape using TensorFlow functions.
rank = tf.rank(tensor)
shape = tf.shape(tensor)

#print rank and shape
print(f"Original Rank: {rank.numpy()}")
print(f"Original Shape: {shape.numpy()}")

Original Rank: 2
Original Shape: [4 6]


In [ ]:
#	Reshape it into (2, 3, 4) and transpose it to (3, 2, 4).

#reshape tensor
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))

# get and print the reshaped_tensor rank and shape
print("\nReshaped Tensor:")
reshaped_rank = tf.rank(reshaped_tensor)
reshaped_shape = tf.shape(reshaped_tensor)
print(f"Reshaped Rank: {reshaped_rank.numpy()}")
print(f"Reshaped Shape: {reshaped_shape.numpy()}")

# transpose tensor
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])

# get and print the transposed_tensor rank and shape
print("\nTransposed Tensor:")
transposed_rank = tf.rank(transposed_tensor)
transposed_shape = tf.shape(transposed_tensor)
print(f"Transposed Rank: {transposed_rank.numpy()}")
print(f"Transposed Shape: {transposed_shape.numpy()}")


Reshaped Tensor (2, 3, 4):
Reshaped Rank: 3
Reshaped Shape: [2 3 4]

Transposed Tensor (3, 2, 4):
Transposed Rank: 3
Transposed Shape: [3 2 4]


In [ ]:
#	Broadcast a smaller tensor (1, 4) to match the larger tensor and add them.

# create a small tensor
smaller_tensor = tf.constant([[1, 2, 3, 4]], dtype=tf.float32)

# brodcast small tensor to the larger tensor and add them
broadcasted_sum = transposed_tensor + smaller_tensor

# compare the tensors and broadcasting result
print("\nSmaller Tensor (1, 4):")
print(smaller_tensor)

print("\nTransposed Tensor (3, 2, 4):")
print(transposed_tensor)

print("\nBroadcasting Sum:")
print(broadcasted_sum)


Smaller Tensor (1, 4):
tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)

Transposed Tensor (3, 2, 4):
tf.Tensor(
[[[-2.1951766   0.8756059   0.608644   -1.7067106 ]
  [-0.6313516  -0.889982   -0.3478521   1.9041904 ]]

 [[ 0.7610917  -0.03532629 -2.1219616  -1.5645102 ]
  [ 0.56109107  0.63317007  0.8806401   0.58040607]]

 [[ 0.18795833  0.32119533 -0.2941246  -0.5941334 ]
  [ 0.19355945 -0.12232149 -0.17201278 -0.02884469]]], shape=(3, 2, 4), dtype=float32)

Broadcasting Sum:
tf.Tensor(
[[[-1.1951766  2.8756058  3.608644   2.2932894]
  [ 0.3686484  1.110018   2.6521478  5.9041905]]

 [[ 1.7610917  1.9646738  0.8780384  2.4354897]
  [ 1.5610911  2.6331701  3.88064    4.580406 ]]

 [[ 1.1879584  2.3211954  2.7058754  3.4058666]
  [ 1.1935594  1.8776785  2.8279872  3.9711554]]], shape=(3, 2, 4), dtype=float32)


Explain how broadcasting works in TensorFlow.

The original smaller tensor has dimensions [1,4]. Broadcasting shifts the dimension of the smaller tensor to the rightmost of the larger tensor ie: [0,1,4]. Tensorflow fills any zero dimensions with a 1 [1,1,4] and then adds copies of the smaller tensor in its missing dimensions to match the larger tensor [3,2,4] 